name: CI

on:
  push:
    branches: [main, master]
    tags: ["*"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.deps }} deps
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ["1.10", "1"]
        os: [ubuntu-latest]
        deps: [latest]
        include:
          - version: "1.10"
            os: ubuntu-latest
            deps: oldest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-downgrade-compat@v1
        if: ${{ matrix.deps == 'oldest' }}
        with:
          skip: Pkg,TOML
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
